quiz_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = 'Quiz Administration'
admin.site.site_title = 'Quiz Administration'
admin.site.index_title = 'Quiz Administration'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quizes.urls', namespace='quizes')),
    path('results', include('results.urls', namespace='results'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quizes/urls.py
from django.urls import path
from .views import QuizListView, QuizDetailView, quiz_data, save_quiz, update_session

app_name = 'quizes'

urlpatterns = [
    path('', QuizListView.as_view(), name='home'),
    path('<int:pk>/', QuizDetailView.as_view(), name='quiz-detail'),
    path('<int:pk>/data/', quiz_data, name='quiz-detail-data'),
    path('<int:pk>/save/', save_quiz, name='quiz-detail-save'),
    path('update_session/', update_session, name='update_session'),
]

results/urls.py
from django.urls import path
from .views import ResultView

app_name = 'results'

urlpatterns = [
    path('', ResultView.as_view(), name='res'),
    
]

questions/models.py
from django.db import models
from quizes.models import Quiz
# Create your models here.

class Question(models.Model):
    text = models.CharField(max_length=150)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.text}'

    def get_answers(self):
        return  self.answer_set.all()
        '''
        with related name :
        return  self.answers.all()
        '''


class Answer(models.Model):
    text = models.CharField(max_length=150)
    correct = models.BooleanField(default=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    '''
    with related name :
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answers')
    '''
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Question - {self.question}. Answer - {self.text}. Correct - {self.correct}'

quizes/models.py
from pyexpat import model
from statistics import mode
from tabnanny import verbose
from django.db import models
from django.urls import reverse
import random

# Create your models here.

DIFFICULTY = (
    ('easy', 'easy'),
    ('medium', 'medium'),
    ('hard', 'hard')
)

class Quiz(models.Model):
    name = models.CharField(max_length=100)
    topic = models.CharField(max_length=100)
    number_of_questions = models.PositiveIntegerField()
    time = models.IntegerField(help_text="Quiz duration in minutes")
    passing_score = models.PositiveIntegerField(help_text="Minimum required % to pass")
    difficulty = models.CharField(max_length=10, choices=DIFFICULTY)

    class Meta:
        verbose_name_plural = 'Quizes'

    def __str__(self):
        return f"{self.name} - {self.topic}"

    def get_questions(self):
        questions = list(self.question_set.all())
        random.shuffle(questions)
        return questions[:self.number_of_questions]

    def get_absolute_url(self):
        return reverse("quizes:quiz-detail", kwargs={"pk": self.pk})
    

results/models.py
from django.db import models
from quizes.models import Quiz
from django.contrib.auth.models import User

# Create your models here.

class Result(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    user = models.CharField(max_length=200)
    score = models.FloatField()

    def __str__(self):
        return f'{self.user} scored {self.score} in {self.quiz.name}'

questions/views.py
from django.shortcuts import render

# Create your views here.

quizes/views.py
import imp
from urllib import request
from django.http import JsonResponse
from django.shortcuts import render
from .models import Quiz
from django.views.generic import ListView, DetailView
from django.db.models import Q
from questions.models import Question
from results.models import Result

# Create your views here.

class QuizListView(ListView):
    model = Quiz

    def get_queryset(self):
        q = self.request.GET.get('q') if self.request.GET.get('q') != None else ''
        qs = Quiz.objects.filter(Q(name__icontains=q) | Q(topic__icontains=q))
        return qs


class QuizDetailView(DetailView):
    model = Quiz


def quiz_data(self, pk):
    quiz = Quiz.objects.get(pk=pk)
    questions = []
    for q in quiz.get_questions():
        answers = []
        for a in q.get_answers():
            answers.append(a.text)
        questions.append({str(q):answers})

    return JsonResponse({
        'data':questions,
        'time':quiz.time,
    })

def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

def save_quiz(request, pk):
    if is_ajax(request):
        questions = []
        data = request.POST
        data = data.dict()
        data.pop('csrfmiddlewaretoken')

        for k in data.keys():
            question = Question.objects.get(text=k)
            questions.append(question)

        user = request.session['name']
        quiz = Quiz.objects.get(pk=pk)

        score = 0
        results = []
        correct_answer = None
        
        for q in questions:
            selected_a = request.POST.get(q.text)
            correct_a = q.get_answers().get(correct=True).text
            if selected_a == correct_a:
                score += 1
            correct_answer = correct_a
            results.append( {str(q.text) : { 
                'correct' : correct_a,
                'selected' : selected_a,
             }})
        
        score = round((score/len(questions)*100),2)
        
        Result.objects.create(quiz=quiz, user=user, score=score )

        if score >= quiz.passing_score:
            return JsonResponse({'test':results, 'pass':True, 'score':score})
        else:
            return JsonResponse({'test':results, 'pass':False, 'score':score})


def update_session(request):
    request.session['name'] = request.POST.get('name')
    return JsonResponse({})

results/views.py
from django.shortcuts import render
from .models import Result
from django.views.generic import ListView
# Create your views here.

class ResultView(ListView):
    model = Result
    ordering = ['-score']
    paginate_by = 5

quizes/templates/quizes/quiz_detail.html
{% extends 'base.html' %}
{% load static %} 

{% block scripts %}
<script src="{% static 'quizes/quiz.js' %}" defer></script>
{% endblock scripts %}

{% block title %}
    {{ object.name }}
{% endblock title %}

{% block content %}
    <div class="row">
        <div class="col"><h3>{{ object.name }}</h3></div>
        <div class="col text-end" id="timer-box">Countdown</div>
    </div>

    
    <form id="quiz-form" class="mt-3 mb-3">
        {% csrf_token %}
        <div id="quiz-box"></div>
        <hr>
        <button type="submit" class="btn btn-primary mt-3">submit</button>
    </form>
{% endblock content %}

quizes/templates/quizes/quiz_list.html
{% extends 'base.html' %}
{% load static %} 

{% block scripts %}
<script src="{% static 'quizes/main.js' %}" defer></script>
{% endblock scripts %}

{% block title %} List {% endblock title %} 

{% block content%}
<hr>

<!-- Modal -->
<div class="modal fade" id="StartQuizModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body" id="modal-body-confirm">
        </div>
        <div class="modal-body">
          {% csrf_token %}
          <label for='username'>Name</label>
          <input type="text" class = "form-control" id='username' style="min-width: 100%"/>
        </div>
        <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-bs-dismiss="modal">No</button>
        <button required type="button" id="start-button" class="btn btn-success">Start</button>
        </div>
    </div>
    </div>
</div>
<form class="header__search" method="GET" action="{% url 'quizes:home' %}">
    <label>
      <svg
        version="1.1"
        xmlns="http://www.w3.org/2000/svg"
        width="32"
        height="32"
        viewBox="0 0 32 32"
      >
        <title>search</title>
        <path
          d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
        ></path>
      </svg>
      <input name="q" placeholder="Search for test ..." />
    </label>
  </form>
  <br>
  <a href="{% url 'results:res' %}">Results</a>
  <hr>
    {% for obj in object_list %} 
        {% comment %} <a href='{{ obj.get_absolute_url }}'>{{ obj }}</a> {% endcomment %}
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-link modal-button" 
                data-bs-toggle="modal" 
                data-bs-target="#StartQuizModal"
                data-pk = "{{ obj.pk }}"
                data-questions = "{{ obj.number_of_questions }}"
                data-time = "{{ obj.time }}"
                data-difficulty = "{{ obj.difficulty }}"
                data-pass = "{{ obj.passing_score }}"
                data-name = "{{ obj.name }}"
                >
            {{ obj }}
        </button>
        <br>
        
    {% endfor %} 
{% endblock content %}

results/templates/results/result_list.html
{% extends 'base.html' %}

{% block content %}
<hr>
<h3>Top Scorers</h3>
<hr>
    {% for obj in object_list %}
    <ul>
        <li>{{ obj }}</li>
    </ul>
    {% endfor %}
    
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="/results?page={{ page_obj.previous_page_number }}">previous</a>
                {% else %}
                    previous
                {% endif %}
                {% comment %} <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span> {% endcomment %}
                {% for num in page_obj.paginator %}
                    <a href="/results?page={{num.number}}">{{ num.number }}</a>
                {% endfor %}
                {% if page_obj.has_next %}
                    <a href="/results?page={{ page_obj.next_page_number }}">next</a>
                {% else %}
                    next
                {% endif %}
            </span>
        </div>
    {% endif %}

{% endblock content %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- favicon -->
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}"/>

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

    <!-- custom css & js-->
    <link rel="stylesheet" href={% static 'style.css' %}>

    {% block scripts %}
    {% endblock scripts %}

    <title>Quiz | {% block title %}{% endblock title %}</title>
  </head>
  <body>
    {% include 'navbar.html' %}
    <div class="container mt-3">
        {% block content %}
        {% endblock content %}
    </div>
  </body>
</html>

templates/navbar.html
{% load static %}
<header class="header header--loggedIn">
  <div class="container">
    <a href="{% url 'quizes:home' %}" class="header__logo">
      <img src="" />
      <h1>Quizes</h1>
    </a>
    <nav class="header__menu">

    </nav>
  </div>
</header>